AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  Video2FramesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: video2frames/
#      Handler: app.handler
#      Runtime: python3.7
      Timeout: 30
      PackageType: Image
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./video2frames
      DockerTag: v1

  LabelFrameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: label_frame/
      Timeout: 30
      PackageType: Image
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./label_frame
      DockerTag: v1


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  Video2FramesFunction:
    Description: "Video2Frames Lambda Function ARN"
    Value: !GetAtt Video2FramesFunction.Arn
  Video2FramesFunctionIamRole:
    Description: "Implicit IAM Role created for Video2FramesFunction"
    Value: !GetAtt Video2FramesFunctionRole.Arn
